### PR TITLE
Iss10

### PR DESCRIPTION
**Pull request by ncr508**
Please, Vicente, look at this. apparently, it works. I'm sure that it could be optimized.

### CODE REVIEW

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @ncr508. It seems that the encoder works. We can say you have solved the half of the issue (the decoder is still pending, right?)!

I'm going to accept the PR, but the iss10 will remain open.

Thanks!

**Comment by ncr508** [comment]
Ouch, @vicente-gonzalez-ruiz it's true. I will try to solve it, too and if I get it, I will notice you. Thanks

**Comment by ncr508** [comment]
@vicente-gonzalez-ruiz I tried it. Could you see my code? I'm sure that it could be optimized by any mate.

**Comment by vicente-gonzalez-ruiz** [comment]
Yes @ncr508, I can see my code and it is now a part of the "official" document. One request. Please, write in English of your comments in your code. Thanks!

**Comment by vicente-gonzalez-ruiz** [comment]
Ah, one thing more. If you are the *source* of the implementation, please, reflect it in a comment. Otherwise, reference the real source.

**Comment by vicente-gonzalez-ruiz** [comment]
BTW (not BWT :-) ), I'm not sure, but it seems that you have added the file `.ipynb_checkpoints/00-fundamentals-checkpoint.ipynb` to your repo. This is a temporal file. As the rule of thumb, temporal files NEVER are included in repositories. Please, remove it (if applicable).

**Pull request merged**
