### PR TITLE
Solved issue 6

### PR DESCRIPTION
**Pull request by sergiocaceres**
You need to install the package bitarray. Like this sudo apt-get install python-bitarray

### CODE REVIEW

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @sergiocaceres. I'm going to reject the PR because: (1) the code is for Python 2.7 and should be for Python 3 (3.6.3, if possible), and (2) you need to provide results for compressing the image files "lena, zelda, ...".

One thing more ... It seems like you have created a issue for that (#18). This is not necessary. You (in fact, all of us) should work on iss6 (not iss18).

Regards,
Vicente.

**Comment by sergiocaceres** [comment]
Hi @vicente-gonzalez-ruiz 

I have been trying this issue with Python3 and the code don´t work because the code that you send us : https://github.com/manassra/LZ77-Compressor/blob/master/src/LZ77.py is done for Python2, so.. there are many problems, for example, with function "frombytes".

I think that there are two options:
1. Left the code in python2
2. Look for another code that is implemented in python3 for to be able to try this algorithm

Thanks!

**Comment by vicente-gonzalez-ruiz** [comment]
Could you translate the code from Python2 to Python3. It should be quite straightforward.

**Comment by sergiocaceres** [comment]
Hi @vicente-gonzalez-ruiz 

I have just done the code for Python 3 :). Could you see it?

On the other hand.. I didnt understand you when you said to me "you need to provide results of compressing the image files". What values? 

Thank you!

**Comment by vicente-gonzalez-ruiz** [comment]
@sergiocaceres, you have done a good job translating the code. But, unfortunately, I have (again) bad news. This code does NOT implement the LZ77 algorithm. I think that is a version of the LZSS algorithm. Try to compress the string of the example and you will see that the code-words are different to the obtained in the example.

Again, I think that it could be quite straightforward to convert it into a pure LZ77.

In relation to the question about the images, see the notebook `01-gzip.ipynb`. There, there is an example of the compression of the images.

**Comment by sergiocaceres** [comment]
Hello @vicente-gonzalez-ruiz , when you say: "his code does NOT implement the LZ77 algorithm. I think that is a version of the LZSS algorithm.".. The code is what you passed us in the issue 6: See https://github.com/manassra/LZ77-Compressor/blob/master/src/LZ77.py

So... I don´t understand why you told us this github if it hasn´t implement the LZ77 algorithm

Thanks!

**Comment by vicente-gonzalez-ruiz** [comment]
It's the closest code to LZ77 I found in the Internet. If I had found a better code, I would have referenced it. 

Apologies for the time (you think) you have lost :-/

**Comment by sergiocaceres** [comment]
Ah, I understand it now ! I will try to change the algorithm 

Thanks!

**Comment by vicente-gonzalez-ruiz** [comment]
@sergiocaceres, let's do the following.

Try to solve the conflicts that at this moment are happening and I'll accept your PR (and I'll close this issue). Later, you (please), create a new one titled "From LZSS to LZ77" or something like that. And, if you want (you means all the class!), start working on this issue.

And, ... don't forget to measure the performance of the implementation compressing the images I've mentioned (lena, pepper, zelda ...).

**Comment by sergiocaceres** [comment]
@vicente-gonzalez-ruiz done!

In the new issue, can I put the title "Convert LZSS to LZ77 and try the algorithm with images"?

Thanks

**Comment by vicente-gonzalez-ruiz** [comment]
Yes, call the issue as you want.

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @sergiocaceres, the merge failed (or I did something wrong) because I can't find your code. Please, could you request again the PR? (Be careful when synchronizing your repo with the original one ("upstream", I think).

Thanks!

**Comment by sergiocaceres** [comment]
Hi @vicente-gonzalez-ruiz , I have just done!

👍

**Pull request merged**
